package com.youcii.mvplearn.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.youcii.mvplearn.model.MovieEntity;

import com.youcii.mvplearn.greendao.MovieEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieEntityDaoConfig;

    private final MovieEntityDao movieEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieEntityDaoConfig = daoConfigMap.get(MovieEntityDao.class).clone();
        movieEntityDaoConfig.initIdentityScope(type);

        movieEntityDao = new MovieEntityDao(movieEntityDaoConfig, this);

        registerDao(MovieEntity.class, movieEntityDao);
    }
    
    public void clear() {
        movieEntityDaoConfig.clearIdentityScope();
    }

    public MovieEntityDao getMovieEntityDao() {
        return movieEntityDao;
    }

}
